Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 17/04/2023
Var

   distancia, combustivel, consumo : real

Inicio

      escreva("Distância percorrida: ")
      leia (distancia)
      escreva("Combustível gasto: ")
      leia (combustivel)
      
      consumo <- distancia / combustivel
      
      escreval("Consumo medio:", consumo:8:3)

Fimalgoritmo